language: node_js
node_js: 
      - "stable"
cache:
  directories:
    - "node_modules"

services: 
      -mongodb

before_script:
  - sleep 15

env:
  global:
    - NODE_ENV=test
    - PORT=9001
    - JWT_SECRET=Hkv6IMQtlOxq7rour7CFniraPrXOBoEZ
    - JWT_EXPIRATION=1d
    - MONGO_URI_TESTS=mongodb://localhost:27017/stackoverflow-mock_test